[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mysqli", "php83Extensions.mbstring", "php83Extensions.openssl", "php83Extensions.session"]

[phases.install]
cmds = ["php -m | grep -i pdo || echo 'PDO not found'"]
